package chapter.three;

/* Generated By:JavaCC: Do not edit this line. MiniJavaParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJavaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLASS = 6;
  /** RegularExpression Id. */
  int IF = 7;
  /** RegularExpression Id. */
  int INT = 8;
  /** RegularExpression Id. */
  int NEW = 9;
  /** RegularExpression Id. */
  int VOID = 10;
  /** RegularExpression Id. */
  int ELSE = 11;
  /** RegularExpression Id. */
  int TRUE = 12;
  /** RegularExpression Id. */
  int MAIN = 13;
  /** RegularExpression Id. */
  int THIS = 14;
  /** RegularExpression Id. */
  int WHILE = 15;
  /** RegularExpression Id. */
  int FALSE = 16;
  /** RegularExpression Id. */
  int PUBLIC = 17;
  /** RegularExpression Id. */
  int STATIC = 18;
  /** RegularExpression Id. */
  int STRING = 19;
  /** RegularExpression Id. */
  int LENGTH = 20;
  /** RegularExpression Id. */
  int RETURN = 21;
  /** RegularExpression Id. */
  int BOOLEAN = 22;
  /** RegularExpression Id. */
  int EXTENDS = 23;
  /** RegularExpression Id. */
  int DIGIT = 24;
  /** RegularExpression Id. */
  int LETTER = 25;
  /** RegularExpression Id. */
  int IDENTIFIER = 26;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"class\"",
    "\"if\"",
    "\"int\"",
    "\"new\"",
    "\"void\"",
    "\"else\"",
    "\"true\"",
    "\"main\"",
    "\"this\"",
    "\"while\"",
    "\"false\"",
    "\"public\"",
    "\"static\"",
    "\"String\"",
    "\"length\"",
    "\"return\"",
    "\"boolean\"",
    "\"extends\"",
    "<DIGIT>",
    "<LETTER>",
    "<IDENTIFIER>",
    "<INTEGER_LITERAL>",
    "\"{\"",
    "\"(\"",
    "\"[\"",
    "\"]\"",
    "\")\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\"System.out.println\"",
    "\"=\"",
    "\"+\"",
    "\".\"",
    "\"!\"",
  };

}
